🩹: Jestでテスト実施前のモッククリア方法を修正 (#1125)
## ✅ What's done

Expo SDK 48アップグレードの対応で、`App.test.tsx`を実行すると以下のエラーが発生

> Error: Hooks cannot be defined inside tests. Hook of type "beforeEach" is nested within

`jest/__mocks__`配下のモックファイルは、モックしているライブラリなどが`import`、`require`されたときに読み込まれます。
テスト対象のコンポーネントの内部で、条件によって`require`するライブラリを切り替えている箇所があり、それが原因でこのエラーが発生したと思われます。

そのため、`jest/__mocks__`配下のモックファイルでモックをクリアするのをやめて、`jest.config.js`の[clearMocks](https://jestjs.io/ja/docs/configuration#clearmocks-boolean)を有効化する方法で、テスト実施前にモックをクリアします。

- [x] `jest.config.js`の`clearMocks`を`true`に設定
- [x] テスト実施前に`beforeEach`や`beforeAll`でモックをクリアしていた箇所を削除
  - 対象は以下で確認
  - [x] `git grep mockClear`
  - [x] `git grep clearAllMocks`